[project]
name = "streamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pygobject>=3.52.3",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.3",
    "uvicorn>=0.35.0",
]
